Import latest version of bag schema from schemas.data.amsterdam.nl
Prevents runserver hanging indefinitely after

    ValueError: Failed to construct field brk.kadastraleobjecten.heeftEenRelatieMetVerblijfsobject:
    Table 'verblijfsobjecten' does not exist in schema 'bag'

when running with a local schema server (docker-compose up schemas).