Bump some dependencies
I scanned the diffs for these and am reasonably sure nothing crazy happens.

pytest-django is not upgraded, since 4.3.0 causes a test failure:

――――――――――――――――――― ERROR at teardown of TestDatabaseSchemasRouter.test_db_for_read_returns_schema_name_if_set ――――――――――――――――――――

cls = <class 'pytest_django.fixtures._django_db_fixture_helper.<locals>.PytestDjangoTestCase'>

    @classmethod
    def tearDownClass(cls):
        if cls._databases_support_transactions():
            cls._rollback_atomics(cls.cls_atomics)
            for conn in connections.all():
                conn.close()
>       super().tearDownClass()

../venv/lib/python3.8/site-packages/django/test/testcases.py:1135:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../venv/lib/python3.8/site-packages/django/test/testcases.py:228: in tearDownClass
    cls._remove_databases_failures()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cls = <class 'pytest_django.fixtures._django_db_fixture_helper.<locals>.PytestDjangoTestCase'>

    @classmethod
    def _remove_databases_failures(cls):
        for alias in connections:
            if alias in cls.databases:
                continue
            connection = connections[alias]
            for name, _ in cls._disallowed_connection_methods:
                method = getattr(connection, name)
>               setattr(connection, name, method.wrapped)
E               AttributeError: 'function' object has no attribute 'wrapped'

../venv/lib/python3.8/site-packages/django/test/testcases.py:224: AttributeError